_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 77
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.13
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
alpha:
    value: 0.1
borf_batch_add:
    value: 20
borf_batch_remove:
    value: 3
dataset:
    value: mutag
display:
    value: true
dropout:
    value: 0.5
encoding:
    value: null
eps:
    value: 0.001
eval_every:
    value: 1
hidden_dim:
    value: 64
last_layer_fa:
    value: false
layer_type:
    value: R-GCN
learning_rate:
    value: 0.001
mlp:
    value: true
num_iterations:
    value: 40
num_layers:
    value: 10
num_splits:
    value: 3
num_trials:
    value: 1
output_dim:
    value: 2
patience:
    value: 100
rewiring:
    value: null
sdrf_remove_edges:
    value: false
