dataset: max_complete
encoding: ""
layer_type: "SAN"
num_trials: 1
num_iterations: 1

input_dim:
output_dim: 
hidden_dim: 64

learning_rate: 1e-3
display: True
eval_every: 1
rewiring: None
patience: 250
output_dim: 2
eps: 0.001,
last_layer_fa: False

san:

graphormer:

exphormer: