dataset:
  - max_complete
  - max_cycle
  - max_path
  - max_regular
  - max_tree
  - min_complete
  - min_cycle
  - min_path
  - min_regular
  - min_tree

layer_type: "SANTransformer"
num_trials: 1
num_iterations: 1

encoding: ""
input_dim: 10
output_dim: 1
hidden_dim: 64

learning_rate: 1.0e-3
display: True
eval_every: 1
patience: 250
output_dim: 2
eps: 0.001

san:
  n_layers: 5
  gamma: 1.0e-5
  n_heads: 4
  full_graph: False
  dropout: 0.0
  layer_norm: False
  batch_norm: False
  residual: False

graphormer:
  n_layers: 5
  n_heads: 4
  dropout: 0.0
  attention_dropout: 0.0
  mlp_dropout: 0.0

exphormer: ~