_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.9.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 77
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.13
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
alpha:
    value: 0.1
borf_batch_add:
    value: 20
borf_batch_remove:
    value: 3
config_path:
    value: config.yml
dataset:
    value: max_complete
display:
    value: true
dropout:
    value: 0.1
encoding:
    value: ""
eps:
    value: 0.001
eval_every:
    value: 1
exphormer:
    value: null
graphormer:
    value: null
hidden_dim:
    value: 64
input_dim:
    value: 1
last_layer_fa:
    value: false
layer_type:
    value: SANTransformer
learning_rate:
    value: "1e-3"
num_iterations:
    value: 1
num_layers:
    value: 16
num_splits:
    value: 3
num_trials:
    value: 1
output_dim:
    value: 1
patience:
    value: 250
rewiring:
    value: null
san:
    value:
        batch_norm: false
        dropout: 0
        full_graph: true
        gamma: "1e-5"
        layer_norm: false
        num_heads: 2
        residual: true
sdrf_remove_edges:
    value: false
